import type { Pack } from './types'

export const PACKS: Pack[] = [
  {
    id: 'complet',
    name: 'Kit Complet',
    subtitle: 'Jour & nuit réunis',
    emoji: '💎',
    price: 24.90,
    priceDisplay: '24,90€',
    tag: 'Le plus populaire',
    tagColor: '#F4A261',
    shortDesc: 'Tout ce qu\'il te faut, du matin au soir 💎',
    longDesc: 'Le Kit Complet réunit Kit Domin et Kit Soley pour une routine beauté créole 100% complète. Protège tes cheveux la nuit et sublime-les le jour — à prix réduit.',
    items: [
      '1 bonnet satin à nœud (rose poudré)',
      '4 chouchous satin (rose & champagne)',
      '1 brosse démêlante douce',
      '1 paire de créoles dorées torsadées',
      '1 pince croco dorée fleur',
      '1 pince croco dorée géométrique',
      '3 bandeaux satin (rose, blanc, beige)',
    ],
    image: '/Kit_Complet.png',
    costPrice: 8.20,
  },
  {
    id: 'nuit',
    name: 'Kit Nuit',
    subtitle: 'La routine nuit',
    emoji: '🌙',
    price: 14.90,
    priceDisplay: '14,90€',
    tag: 'Le plus populaire',
    tagColor: '#C8435A',
    shortDesc: 'Prends soin de tes cheveux pendant ton sommeil 🌙',
    longDesc: 'Réveille-toi avec des cheveux sublimes. Le Kit Domin protège tes cheveux la nuit grâce au satin qui réduit les frottements, limite la casse et garde ton style intact jusqu\'au matin.',
    items: [
      '1 bonnet satin à nœud (rose poudré)',
      '4 chouchous satin (rose & champagne)',
      '1 brosse démêlante douce',
    ],
    image: '/Kit_Nuit.png',
    costPrice: 3.75,
  },
  {
    id: 'jour',
    name: 'Kit Jour',
    subtitle: 'Les essentiels du jour',
    emoji: '✨',
    price: 12.90,
    priceDisplay: '12,90€',
    tag: 'Nouveau',
    tagColor: '#2D6A4F',
    shortDesc: 'Sublimes ta coiffure au quotidien ✨',
    longDesc: 'Des accessoires dorés qui s\'accordent avec tout. Le Kit Soley réunit les essentiels pour coiffer, attacher et sublimer tes cheveux du matin jusqu\'au soir, avec une touche dorée créole.',
    items: [
      '1 paire de créoles dorées torsadées',
      '1 pince croco dorée fleur',
      '1 pince croco dorée géométrique',
      '3 bandeaux satin (rose, blanc, beige)',
    ],
    image: '/Kit_Jour.png',
    costPrice: 4.45,
  },
]
